show_excerpts: true
title: Opacity Zero
logo: logo.png
email: opacityzero.press@gmail.com
description: >- # this means to ignore newlines until "baseurl:
  Opacity Zero is a show about challenging the unknown with curiosity. About
  unanswered questions, controversial answers and the need for a little bit of
  certainty in a world where nothing seems certain at all.
baseurl: "/opacityzero" # the subpath of your site, e.g. /blog
url: "sheymans.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: opacity0press
# github_username:  sheymans

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme
remote_theme: jekyll/minima

minima:
  social_links:
    twitter: opacity0press
    facebook: pages/Opacity-Zero/858503340907496   
  skin: solarized
  site:
    author:
      name: Melanie Heymans
      email: opacityzero.press@gmail.com

google_analytics: G-X7HCGETEB8
