show_excerpts: true
title: Opacity Zero – Challenging the Unknown with Curiosity
logo: logo.png
email: opacityzero.press@gmail.com
description: >- # this means to ignore newlines until "baseurl:
  Opacity Zero is a show about challenging the unknown with curiosity. About
  unanswered questions, controversial answers and the need for a little bit of
  certainty in a world where nothing seems certain at all.
url: "opacityzero.press" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
plugins:
  - jekyll-feed
  - jekyll-remote-theme
remote_theme: jekyll/minima

minima:
  social_links:
    twitter: opacity0press
    facebook: pages/Opacity-Zero/858503340907496   
  skin: solarized
  site:
    author:
      name: Melanie Heymans
      email: opacityzero.press@gmail.com

google_analytics: UA-64746620-1
